// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVcRDpJ31x6ZpETQQzpZBzqJaOtiXCZg',
    appId: '1:147852764562:web:1cb7d088348cda15538d4b',
    messagingSenderId: '147852764562',
    projectId: 'odiorent-notifications',
    authDomain: 'odiorent-notifications.firebaseapp.com',
    storageBucket: 'odiorent-notifications.firebasestorage.app',
    measurementId: 'G-40LSKCW13L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAn_l7AmRlMfpCypmbRsuuGrcHtQuCE-I',
    appId: '1:147852764562:android:26c7c09cb1c5298f538d4b',
    messagingSenderId: '147852764562',
    projectId: 'odiorent-notifications',
    storageBucket: 'odiorent-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJr9DoBexBC_qeoSA-QvXBY1P-tqc9w8',
    appId: '1:147852764562:ios:1d8a878cef2db24a538d4b',
    messagingSenderId: '147852764562',
    projectId: 'odiorent-notifications',
    storageBucket: 'odiorent-notifications.firebasestorage.app',
    iosBundleId: 'com.example.odiorent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJr9DoBexBC_qeoSA-QvXBY1P-tqc9w8',
    appId: '1:147852764562:ios:1d8a878cef2db24a538d4b',
    messagingSenderId: '147852764562',
    projectId: 'odiorent-notifications',
    storageBucket: 'odiorent-notifications.firebasestorage.app',
    iosBundleId: 'com.example.odiorent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOVcRDpJ31x6ZpETQQzpZBzqJaOtiXCZg',
    appId: '1:147852764562:web:1ce78173c8047fc2538d4b',
    messagingSenderId: '147852764562',
    projectId: 'odiorent-notifications',
    authDomain: 'odiorent-notifications.firebaseapp.com',
    storageBucket: 'odiorent-notifications.firebasestorage.app',
    measurementId: 'G-C47PRGCPQK',
  );
}
